spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 5d2abdd50839cb329bfb
            client-secret: 1022a364fbcf21f7500a2d0b7c88f788c0b9886a
          facebook:
            client-id: 805478719657122
            client-secret: 9c20ab2c5baa26bad952f7cdf05607c6
